site_name: My Docs
site_name: 溶err
site_url: https://mydomain.org/mysite
# theme:
#   name: material
#   palette:
#     primary: light blue  # 主题颜色
#     accent: light blue   # 设置鼠标悬停

nav:
# 为了将页面链接到某个部分，
# 请在相应的文件夹中创建一个名为 index.md 的新文档，
# 并将其添加到导航部分的开头

  - home:
    - index.md 
    - Page 1: home/page-1.md
    - Page 2: home/page-2.md
  - 便签:
    - 备忘录: 便签/备忘.md
    - TODO: 便签/TODO.md
    - mkdocs_learn: 便签/mkdocs_learn.md
  - Leecode:
    - 力扣: Leecode/力扣.md
  - Error:
    - 报错 : Error/报错.md    

theme:
  name: material
  features:  
    - navigation.tabs  # 设置导航
    - navigation.tabs.sticky # 粘性导航
    - navigation.sections # 不知道是啥 加上试一下  
    # 功能标志 navigation.tabs 和 navigation.sections 可以相互组合。
    # 如果启用了两个功能标志，则会为级别 2 导航项呈现部分。
    - navigation.expand  # 下拉的导航默认展开
    - navigation.indexes # 索引页
  palette: 
    # Palette toggle for light mode 设置白天模式
    - scheme: default
      primary: light blue  # 设置横幅颜色
      accent: light blue  # 设置鼠标悬停颜色
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode  设置夜间模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_url: https://github.com/squidfunk/mkdocs-material # 添加github仓库，跟theme是同一个级别
repo_name: squidfunk/mkdocs-material # 设置存储库的名称  就会出现了 mkdocs-material这个仓库，并自动读取一些开源仓库的基本信息